### ISSUE TITLE
Inspector does not work correctly.

### ISSUE THREAD

**Issue by rand0mC0d3r** [SeregPie/aframe-text-sprite#3]
It throws a ""Raycaster.camera" needs to be set in order to raycast against sprites."

Reproduce
```
<head>
  <title>My A-Frame Scene</title>
  <script src="https://unpkg.com/aframe"></script>
  <script src="https://unpkg.com/aframe-text-sprite"></script>
</head>

<body>
  <a-scene>
    <a-box id="box" color="red" depth="2" height="4" position="0 0 -4" width="0.5"></a-box>
    <a-entity id="textt" position="0 0 -3" text-sprite="color: #000000; text: aaaa"></a-entity>
  </a-scene>
</body>
```

expected
to work

**Comment by rand0mC0d3r** [comment]
https://github.com/mrdoob/three.js/pull/16423
https://github.com/mrdoob/three.js/issues/17078

those 2 links seem to help

**Comment by SeregPie** [comment]
Hi.

https://threejs.org/docs/index.html#api/en/objects/Sprite.raycast
```
The raycaster must be initialized by calling Raycaster.setFromCamera() before raycasting against sprites.
```

Changing the raycaster from the inside of this component looks more like a hack for me.

This should be done inside AFRAME somehow.

https://github.com/aframevr/aframe/blob/1fc08e429cef92fe53042ae08846c209889c30e5/src/components/raycaster.js

**Comment by SeregPie** [comment]
Ok. I don't think AFrame will fix this anytime soon, so I made a little fix.
